### ISSUE TITLE
`yarn run generate` crashes on netlify

### ISSUE THREAD

**Issue by PieterjanMontens** [openjusticebe/omdat#2]
Message d'erreur:

```
2:58:10 PM: $ yarn run generate
2:58:10 PM: yarn run v1.22.10
2:58:10 PM: $ nuxt generate
2:58:10 PM: [warn] For using `nuxt generate`, your have to set `target: 'static'` in your `nuxt.config`
2:58:10 PM:        👉 Learn more about it on https://go.nuxtjs.dev/static-target
2:58:11 PM: [fatal] Cannot find module '@nuxtjs/vuetify'
2:58:11 PM: Require stack:
2:58:11 PM: - /opt/build/repo/node_modules/@nuxt/core/dist/core.js
2:58:11 PM: - /opt/build/repo/node_modules/@nuxt/cli/dist/cli-index.js
2:58:11 PM: - /opt/build/repo/node_modules/@nuxt/cli/dist/cli.js
2:58:11 PM: - /opt/build/repo/node_modules/nuxt/bin/nuxt.js
2:58:11 PM:   Error: Cannot find module '@nuxtjs/vuetify'
2:58:11 PM:   Require stack:
2:58:11 PM:   - node_modules/@nuxt/core/dist/core.js
2:58:11 PM:   - node_modules/@nuxt/cli/dist/cli-index.js
2:58:11 PM:   - node_modules/@nuxt/cli/dist/cli.js
2:58:11 PM:   - node_modules/nuxt/bin/nuxt.js
2:58:11 PM:   at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:615:31)
2:58:11 PM:   at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:180:38)
2:58:11 PM:   at node_modules/@nuxt/utils/dist/utils.js:1846:43
2:58:11 PM:   at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
2:58:11 PM:   at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:715:5)
2:58:11 PM: 
2:58:11 PM:    ╭────────────────────────────────────────────────────────────────╮
2:58:11 PM:    │                                                                │
2:58:11 PM:    │   ✖ Nuxt Fatal Error                                           │
2:58:11 PM:    │                                                                │
2:58:11 PM:    │   Error: Cannot find module '@nuxtjs/vuetify'                  │
2:58:11 PM:    │   Require stack:                                               │
2:58:11 PM:    │   - /opt/build/repo/node_modules/@nuxt/core/dist/core.js       │
2:58:11 PM:    │   - /opt/build/repo/node_modules/@nuxt/cli/dist/cli-index.js   │
2:58:11 PM:    │   - /opt/build/repo/node_modules/@nuxt/cli/dist/cli.js         │
2:58:11 PM:    │   - /opt/build/repo/node_modules/nuxt/bin/nuxt.js              │
2:58:11 PM:    │                                                                │
2:58:11 PM:    ╰────────────────────────────────────────────────────────────────╯
2:58:11 PM: 
2:58:11 PM: error Command failed with exit code 1.
2:58:11 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2:58:11 PM: ​
2:58:11 PM: ────────────────────────────────────────────────────────────────
2:58:11 PM:   "build.command" failed                                        
2:58:11 PM: ────────────────────────────────────────────────────────────────
2:58:11 PM: ​
2:58:11 PM:   Error message
2:58:11 PM:   Command failed with exit code 1: yarn run generate
2:58:11 PM: ​
2:58:11 PM:   Error location
2:58:11 PM:   In Build command from Netlify app:
2:58:11 PM:   yarn run generate
2:58:11 PM: ​
2:58:11 PM:   Resolved config
2:58:11 PM:   build:
2:58:11 PM:     command: yarn run generate
2:58:11 PM:     commandOrigin: ui
2:58:11 PM:     publish: /opt/build/repo/dist
```

**Comment by PieterjanMontens** [comment]
Ah, pareil avec `yarn run build`

**Comment by tintamarre** [comment]
Dropping nuxtjs
